#pragma once
#if !defined(GRADIENT_PALETTES_HPP)
#define GRADIENT_PALETTES_HPP

DECLARE_GRADIENT_PALETTE( ib_jul01_gp );
DECLARE_GRADIENT_PALETTE( es_vintage_57_gp );
DECLARE_GRADIENT_PALETTE( es_vintage_01_gp );
DECLARE_GRADIENT_PALETTE( es_rivendell_15_gp );
DECLARE_GRADIENT_PALETTE( rgi_15_gp );
DECLARE_GRADIENT_PALETTE( retro2_16_gp );
DECLARE_GRADIENT_PALETTE( Analogous_1_gp );
DECLARE_GRADIENT_PALETTE( es_pinksplash_08_gp );
DECLARE_GRADIENT_PALETTE( es_pinksplash_07_gp );
DECLARE_GRADIENT_PALETTE( Coral_reef_gp );
DECLARE_GRADIENT_PALETTE( es_ocean_breeze_068_gp );
DECLARE_GRADIENT_PALETTE( es_ocean_breeze_036_gp );
DECLARE_GRADIENT_PALETTE( departure_gp );
DECLARE_GRADIENT_PALETTE( es_landscape_64_gp );
DECLARE_GRADIENT_PALETTE( es_landscape_33_gp );
DECLARE_GRADIENT_PALETTE( rainbowsherbet_gp );
DECLARE_GRADIENT_PALETTE( gr65_hult_gp );
DECLARE_GRADIENT_PALETTE( gr64_hult_gp );
DECLARE_GRADIENT_PALETTE( GMT_drywet_gp );
DECLARE_GRADIENT_PALETTE( ib15_gp );
DECLARE_GRADIENT_PALETTE( Fuschia_7_gp );
DECLARE_GRADIENT_PALETTE( es_emerald_dragon_08_gp );
DECLARE_GRADIENT_PALETTE( lava_gp );
DECLARE_GRADIENT_PALETTE( fire_gp );
DECLARE_GRADIENT_PALETTE( Colorfull_gp );
DECLARE_GRADIENT_PALETTE( Magenta_Evening_gp );
DECLARE_GRADIENT_PALETTE( Pink_Purple_gp );
DECLARE_GRADIENT_PALETTE( Sunset_Real_gp );
DECLARE_GRADIENT_PALETTE( es_autumn_19_gp );
DECLARE_GRADIENT_PALETTE( BlacK_Blue_Magenta_White_gp );
DECLARE_GRADIENT_PALETTE( BlacK_Magenta_Red_gp );
DECLARE_GRADIENT_PALETTE( BlacK_Red_Magenta_Yellow_gp );
DECLARE_GRADIENT_PALETTE( Blue_Cyan_Yellow_gp );

#endif
